### ISSUE TITLE
Is there any sample?

### ISSUE THREAD

**Issue by vrbvillor** [acrazing/Zepto.ajaxFileUpload#2]
Because I'm not familiar with this plugin, would you like to build a sample code using this plugin?

**Comment by acrazing** [comment]
well, good idea. see <example/index.html>

**Comment by vrbvillor** [comment]
no `progress` event or `success` or `fail` ?

**Comment by acrazing** [comment]
will, you can add any params same to `$.ajax`, just like `success`, `error`, `complete`, `dataType`, etc. see <https://github.com/acrazing/Zepto.ajaxFileUpload/blob/master/Zepto.ajaxFileUpload.js#L63-L65>. the different is that we cannot get any response structure in call back like header, status, statusText, etc.

**Comment by vrbvillor** [comment]
Can I get the percentage of the file uploading?

**Comment by acrazing** [comment]
This way cannot do it, you can use `XMLHttpRequest Level 2`(see <https://www.w3.org/TR/2012/WD-XMLHttpRequest-20120117/>) to upload file with `File Api`(see <https://www.w3.org/TR/FileAPI/>) and listen `onprogress`(see https://www.w3.org/TR/2012/WD-XMLHttpRequest-20120117/#handler-xhr-onprogress) event to handle it.

Please be careful that the `iOS 5-` and `android 4-` doesn't support it.

**Comment by vrbvillor** [comment]
Thanks a lot , I'll try it .
